/* OUTER JOIN */

-- STDTBL
CREATE TABLE STDTBL(
	STDNAME NVARCHAR(10) NOT NULL PRIMARY KEY,
    ADDR    NCHAR(4)  NOT NULL
);

CREATE TABLE CLUBTBL(
	CLUBNAME NVARCHAR(10) NOT NULL PRIMARY KEY, 
    ROONO    NCHAR(4)  NOT NULL
);

CREATE TABLE STDCLUBTBL (
	NUM INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STDNAME NVARCHAR(10)  NOT NULL,
    CLUBNAME NVARCHAR(10)  NOT NULL,
    FOREIGN KEY(STDNAME) REFERENCES STDTBL(STDNAME),
    FOREIGN KEY(CLUBNAME) REFERENCES CLUBTBL(CLUBNAME)
);
