-- 뷰 
USE SQLDB;

CREATE VIEW UV_POTENTIALUSER
AS 
	SELECT U.* 
         , B.NUM, B.PRODNAME, B.PRICE, B.AMOUNT
      FROM USERTBL AS U 
      LEFT OUTER JOIN BUYTBL AS B 
        ON U.USERID = B.USERID
	 WHERE B.USERID IS NULL;

SELECT * FROM UV_POTENTIALUSER;