USE TABLEDB;

CREATE TABLE TBL1(
	ID INT NOT NULL PRIMARY KEY, 
    BRIDGE INT NULL, 
    CONTENTS VARCHAR(5000)
);

-- SQL DB의 USERTBL 데이터중
-- USERID, NAME, BIRTHYQEAR, ADDR만 가져와서 
-- TABLEDB.USERTBL에 부어넣은것 
INSERT INTO TABLEDB.USERTBL 
SELECT USERID, NAME, BIRTHYEAR, ADDR
  FROM SQLDB.USERTBL;

-- INDEX를 걸어서 찾기 !! 
-- NULL이 많은 곳에는 XXX
-- 중복이 많은 곳에서는 INDEX는 효과 X
SELECT * FROM USERTBL WHERE NAME = '김범수';

--  JOIN에 자주 사용되는 열에는 INDEX를 생성해주는 것이 좋음 !

